name: Publish NPM Package
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: v1.x

      - name: check format
        run: deno fmt --check

      - name: check linting
        run: deno lint

      - name: build npm package
        run: deno run -A _build_npm.ts ${{ github.ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: publish npm package
        run: |
          cd npm
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}